---

- name: Install collections and roles together
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: requirements.yml

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ srcdir }}/yay"
    update: true

- name: Build and install yay
  command:
    chdir: "{{ srcdir }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay

- name: Install fonts
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - ttf-hack-nerd
    state: present

- name: Install apps
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - neofetch
      - firefox
      - discord
      - thunderbird
      - zathura
      - zathura-pdf-mupdf
      - mpv
      - yt-dlp
      - jgmenu
      - playerctl
        # - nextcloud-client
    state: present
