---

- name: Install collections and roles together
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: requirements.yml

- name: Install necessary packages
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - picom
      - neofetch
      - kitty
      - zsh
      - polybar
      - dunst
      - zathura
      - zathura-pdf-mupdf
      - firefox
      # packages needed for neovim
      - neovim
      - nodejs
      - npm
      - python-pip
      - python-pynvim
      
    state: present

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ srcdir }}/yay"
    update: true

- name: Build and install yay
  command:
    chdir: "{{ srcdir }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
    
- name: Install required package with yay
  kewlfft.aur.aur:
    use: yay
    name:
      - i3-gaps-rounded-git
      - ttf-hack
      - nerd-fonts-hack

