---
- name: Install i3
  kewlfft.aur.aur:
    use: yay
    name:
      - i3-gaps-rounded-git

- name: Install DE
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - picom
      - dunst
      - polybar
      - sddm
      - rofi
      - redshift

- name: Setting up config
  ansible.builtin.file:
    src: '{{configdir}}/{{ item }}'
    dest: '{{ configdest }}/{{ item }}'
    state: link
  loop:
    - i3
    - polybar
    - dunst
    - picom
    - rofi
    - redshift

- name: Setting up .xinitrc & .xprofile
  ansible.builtin.file:
    src: '{{configdir}}/{{ item }}'
    dest: '{{ homedir }}/{{ item }}'
    state: link
  loop:
    - .xinitrc
    - .xprofile

