---
- name: Install neovim
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - neovim
      - nodejs
      - npm
      - python-pip
      - python-pynvim
      - ripgrep
    state: present

- name: Configuring neovim
  ansible.builtin.file:
    src: '{{ configdir }}/nvim'
    dest: '{{ configdest }}/nvim'
    state: link
