---
- name: Install neovim
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - neovim
      - nodejs
      - npm
      - python-pip
      - python-pynvim
    state: present

- name: Configuring neovim
  ansible.builtin.file:
    src: '/home/sofamaniac/dotfiles/nvim'
    dest: '/home/sofamaniac/.config/nvim'
    state: link
