---
- name: Configuring SDDM
  become: yes
  become_user: root
  block:
    - name: Installing required dependecies for SDDM theme
      community.general.pacman:
        name:
          - qt5-graphicaleffects
          - qt5-svg
          - qt5-quickcontrols2
        state: present

    - name: Moving theme to /usr/share/sddm/themes/
      ansible.builtin.copy:
        src: "{{ dotfilesdir }}/catppuccin_sddm/src/catppuccin-macchiato"
        dest: "/usr/share/sddm/themes/"

    - name: Moving configuration to /etc
      ansible.builtin.file:
        state: link
        src: "{{ configdir }}/sddm.conf.d"
        dest: "/etc/sddm.conf.d"

