---
- name: Install utilities
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - kitty
      - zsh
      - syncthing
      - tailscale
      - udisks2
      - networkmanager
      - network-manager-applet
      - tree
      - openssh
      - bat
      - ctags
      - btop
      - man
    state: present

- name: Setting up services
  become: yes
  become_user: root
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  loop:
      - syncthing@sofamaniac.service
      - tailscaled.service

- name: Configuring kitty
  ansible.builtin.file:
    src: '{{ configdir }}/kitty'
    dest: '{{ configdest }}/kitty'
    state: link

- name: Configuring zsh
  ansible.builtin.file:
    src: '{{ configdir }}/{{ item }}'
    dest: '{{ homedir }}/{{ item }}'
    state: link
  loop:
    - .zshrc
    - .zsh_aliases
    - .zshenv
    - .zprofile

- name: Setting up audio
  become: yes
  become_user: root
  ansible.builtin.package:
    name:
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - pavucontrol
    state: present

