#!/bin/bash
# scripts by adi1090x

## Get data
if test -f /var/tmp/player_selector; then
	PLAYER=$(cat /var/tmp/player_selector)
else
	PLAYER=""
fi
if test $PLAYER = "default" || test -z $PLAYER; then
	CMD="playerctl"
else
	CMD="playerctl -p $PLAYER"
fi
STATUS="$($CMD -s status)"
COVER="/tmp/.music_cover.png"
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
	if [[ $STATUS == *"Playing"* ]]; then
		echo "󰏤"
	else
		echo "󰐊"
	fi
}

## Get song
get_song() {
	song=`$CMD -s metadata xesam:title`
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=`$CMD -s metadata xesam:artist`
	if [[ -z "$artist" ]]; then
		echo ""
	else
		echo "$artist"
	fi	
}

## Get time
get_time() {
	time=`mpc status | grep "%)" | awk '{print $4}' | tr -d '(%)'`
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
	ctime=`$CMD -s position --format "{{ position }}"`
	if [[ -z "$ctime" ]]; then
		ctime="00:00"
	else
		ctime=$(echo $ctime | awk '{ printf "%02d:%02d\n", $1 / 60, $1 % 60 }')
	fi
	echo $ctime
}
get_ttime() {
	ttime=`$CMD -s metadata mpris:length`
	if [[ -z "$ttime" ]]; then
		ttime="00:00"
	else
		ttime=$(($ttime / 1000000))
		ttime=$(echo $ttime | awk '{ printf "%02d:%02d\n", $1 / 60, $1 % 60 }')
	fi
	echo $ttime
}

## Get cover
get_cover() {
	COVER=`$CMD -s metadata mpris:artUrl`
	# Check if the file has a embbeded album art
	if [ -n "$COVER" ];then
		echo "$COVER"
	else
		echo "images/music.png"
	fi
}

## control player
player_ctl() {
	$CMD $1
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	{ player_ctl "play-pause"; }
elif [[ "$1" == "--next" ]]; then
	{ player_ctl "next"; }
elif [[ "$1" == "--prev" ]]; then
	{ player_ctl "previous"; }
fi
